Add testrunner images

diff --git a/test/run b/test/run
--- a/test/run
+++ b/test/run
@@ -1,4 +1,50 @@
 #!/usr/bin/env bash
-set -e
-[[ ! -f test/bats/bin/bats ]] && git submodule update --init --recursive
-test/bats/bin/bats "${@:-test}"
+set -euo pipefail
+
+[[ -f test/bats/bin/bats ]] || git submodule update --init --recursive
+
+run_tests_locally() {
+	test/bats/bin/bats "${@:-test}"
+}
+
+run_tests_in_container() {
+	local target="$1"; shift
+	local containerfile="${target%:*}"
+	local tag="${target##*:}"
+
+	test/container-cmd build \
+		--tag "hose/testrunner/${containerfile}/${tag}" \
+		--build-arg TAG="${tag}" \
+		--file "test/testrunners/${containerfile}" \
+		"test"
+
+	test/container-cmd run --rm -it \
+		-v "${PWD}":/usr/src/project \
+		-w /usr/src/project \
+		"hose/testrunner/${containerfile}/${tag}" \
+		test/bats/bin/bats "$@"
+}
+
+main() {
+	local options OPTARG
+	local -i OPTIND
+	local target="local"
+	local -i no_shellcheck=0
+	while getopts "st:" options; do
+		case "${options}" in
+			s) no_shellcheck=1 ;;
+			t) target="${OPTARG}" ;;
+			*) echo "$0: Invalid option: -${OPTARG}" ;;
+		esac
+	done
+	shift $(( OPTIND - 1 ))
+
+	case "${target}" in
+		local) run_tests_locally "${@:-test}" ;;
+		*) run_tests_in_container "${target}" "${@:-test}" ;;
+	esac
+
+	(( no_shellcheck )) || test/shellcheck
+}
+
+main "$@"
